apiVersion: v1
kind: Service
metadata:
  name: wep-svc
spec:
  type: LoadBalancer
  selector:
    app: web-calcu
  ports:
  - protocol: TCP
    port: 80          # This is the port exposed to the outside world
    targetPort: 80
